### ISSUE TITLE
As a user, I want the elements in the experience to have pleasing micro-interactions.

### ISSUE THREAD

**Issue by ChristopherSterza** [Deforestation-Detector/web#45]

**Comment by geoochoa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/web/45?planning-poker) with ZenHub @ChristopherSterza @Donovanphenry @JMBeresford @sedwardsmarsh
