### ISSUE TITLE
Display the full tileset image on investigate page

### ISSUE THREAD

**Issue by ChristopherSterza** [Deforestation-Detector/web#57]

**Comment by geoochoa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/B-Team-61e8d10e780706001425c8a1/issues/Deforestation-Detector/web/57?planning-poker) with ZenHub @sedwardsmarsh @ChristopherSterza @JMBeresford @Donovanphenry
